name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # 在 main 分支推送时触发工作流

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 检出代码
      - name: Checkout code
        uses: actions/checkout@v2

      # 设置 Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to aliyun private docker Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ALIYUN_REGISTRY }} #第2步骤图中的 登录阿里云的地址
          username: ${{ secrets.ALIYUN_REGISTRY_USER }} #你的阿里云账号
          password: ${{ secrets.ALIYUN_REGISTRY_PASSWORD }} #你的镜像仓库密码，好像可以是阿里云账号密码，也可以设置独立的密码

      - name: Build and push noderunner image to ACR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/noderunner:latest #第2步骤图中的 第3小点的地址
          target: noderunner

      - name: Build and push alpine image to ACR
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.ALIYUN_REGISTRY }}/${{ secrets.ALIYUN_NAME_SPACE }}/alpine:latest #第2步骤图中的 第3小点的地址
          target: alpine

      # 登录到 Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub 用户名
          password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub 密码（存储在 Secrets 中）

      # 构建并推送 noderunner 镜像
      - name: Build and push noderunner image to Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .  # 构建上下文目录
          push: true  # 是否推送到 Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/noderunner:latest  # 镜像标签
          target: noderunner

      # 构建并推送 alpine 镜像
      - name: Build and push alpine image t Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .  # 构建上下文目录
          push: true  # 是否推送到 Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/alpine:latest  # 镜像标签
          target: alpine

      # 构建并推送 ubuntu 镜像
      - name: Build and push ubuntu image t Docker Hub
        uses: docker/build-push-action@v6
        with:
          context: .  # 构建上下文目录
          push: true  # 是否推送到 Docker Hub
          tags: ${{ secrets.DOCKER_USERNAME }}/ubuntu:latest  # 镜像标签
          target: ubuntu
